### ISSUE TITLE
how to configure swooletw/laravel-swoole in laradock supervisor

### ISSUE THREAD

**Issue by wen-gg** [swooletw/laravel-swoole#449]
how to configure swooletw/laravel-swoole in laradock supervisor, or are there other methods, thank you！

**Comment by Arkanius** [comment]
Hi there.

I don't know if I understood your needs, but, here's an example of **docker-compose.yml** that I use to run in my projects (locally)

yml
```
version: '2'

services:
  app:
    command: "true"
    image: alpine:3.4
    volumes:
      - ./:/var/www/app
    links:
      - mysql
    networks:
      - app-network

  php:
    image: vtrgomes/composer-alpine:7.4-swoole
    ports:
      - 80:80
    volumes:
      - ./composer-cache:/composer/cache
    volumes_from:
      - app
    networks:
      - app-network
    links:
      - mysql
      - redis

  redis:
    image: vtrgomes/redis-alpine:latest
    volumes:
      - ./redis-data:/data
    ports:
      - 6379:6379
    networks:
      - app-network

  mysql:
    image: vtrgomes/mysql-57:latest
    volumes:
      - ./db-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: core
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    expose:
      - 3306
    ports:
      - 3306:3306
    networks:
      - app-network

volumes:
  composer-cache:
    driver: local

networks:
  app-network:
    driver: bridge

```

All images are from this repo: https://github.com/Arkanius/docker-images
